# Generated by Django 6.0.6 on 2026-06-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('Site_name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('SensorID', models.JSONField(default=list)),
            ],
        ),
    ]
