# Generated by Django 6.0.6 on 2026-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensing',
            name='passhash',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sensing',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
