# Generated by Django 6.0.6 on 2026-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sensing_passhash_sensing_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensing',
            name='protocol',
            field=models.CharField(default='http', max_length=8),
        ),
    ]
